### ISSUE TITLE
[BUG] Wrong menu underlining

### ISSUE THREAD

**Issue by bwbroersma** [bikkelhart/internet-nl#78]
- https://dev3.internet.nl/test-site/
- https://dev3.internet.nl/test-mail/
- https://dev3.internet.nl/test-connection/

All 3 pages underline 'Knowledge base' instead of 'Test tools':
![Image](https://github.com/user-attachments/assets/221ac019-ef1a-423d-ae49-a523dff9f6d7)

Weird since https://github.com/bikkelhart/internet-nl/commit/3e5e21f3f01fa2881ac6af2b22bfd07d485f9e0e is quite an old fix.

**Comment by Khdulkadir** [comment]
This is only the case on dev3 and has been fixed a couple months ago in [bikkelhart-redseign](https://github.com/bikkelhart/internet-nl/tree/bikkelhart-redesign)

**Comment by bikkelhart-menno** [comment]
@Khdulkadir Dev3 is bikkelhart-redesign. Locally this seems to work but not on dev3 for me.

**Comment by bwbroersma** [comment]
I will test with `make develop`.

**Comment by bwbroersma** [comment]
Still not working on dev3, still need to test with `make develop`.

**Comment by bwbroersma** [comment]
Still wrongly underlining "Knowledge base" while active at a 'test'  https://dev3.internet.nl/test-site/
